name: Push to Another Repository
on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - '_posts/**.md'

jobs:
  push-to-b-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Push to b repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: '_posts'
          destination-github-username: 'dangehub'
          destination-repository-name: 'dangehub.github.io'
          user-email: moruotaiqing@gmail.com
          target-branch: master
