name: Push to Another Repository
on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - '_posts/**.md'

jobs:
  push-to-b-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout a repo
        uses: actions/checkout@v3
        with:
          repository: dangehub/github2wp
          path: github2wp
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Checkout b repo
        uses: actions/checkout@v3
        with:
          repository: dangehub/dangehub.github.io
          path: dangehub.github.io
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Copy files from a to b local
        run: |
          cp -r github2wp/_posts/* dangehub.github.io/_posts/       
          cd dangehub.github.io
      - name: Commit and push
        run: |
          git config --global user.name 'dangehub'
          git config --global user.email 'moruotaiqing@gmail.com'
          git add _posts/
          git commit -m "Synced posts" || exit 0
          git push
