name: Push to Another Repository
on:
  push:
    branches:
      - main 
    paths:
      - '_posts/**.md'

jobs:
  push-to-b-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout b repo
        uses: actions/checkout@v2
        with:
          repository: dangehub/dangehub.github.io
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Push to b repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        with:
          source-directory: _post/
          destination-repository: dangehub/dangehub.github.io
          destination-branch: main
          github-token: ${{ secrets.ACCESS_TOKEN }}
